aboutall_blog/urls.py
from django.urls import path, include
from . import views

app_name = 'aboutall_blog' # this name goes to html for separate names in aplications

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:post_id>/', views.detail, name='detail'), # passing post_id to func detail in views
]

personal_portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('cv/', views.cv, name='cv'),
    path('aboutall_blog/', include('aboutall_blog.urls')),
    path('contacts/', views.contacts, name='contacts')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutall_blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Aboutall(models.Model):
    post_title = models.CharField(max_length=100)
    post_description = models.CharField(max_length=250)
    post_fulltext = models.TextField()
    # post_author = models.ForeignKey(User, on_delete=models.CASCADE,)
    post_author = models.CharField(max_length=50)
    post_create_at = models.DateField()

    def __str__(self):
        return self.post_title # to show title instead 'Object 1'

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/image')  # upload_to - where we will save image
    url = models.URLField(blank=True)  # blank=True - field  can be empty

    def __str__(self):
        return self.title # to show title instead 'Object 1'

aboutall_blog/views.py
from django.shortcuts import render, get_object_or_404

from aboutall_blog.models import Aboutall


def all_blogs(request):
#    posts = Aboutall.objects.all()
    posts = Aboutall.objects.order_by('-post_create_at') # [:5] ordered bu date and showing just 5 posts
    return render(request, 'aboutall_blog/all_blogs.html', context={'posts': posts}) # 'posts' goas to html file

def detail(request, post_id):
    blog_post = get_object_or_404(Aboutall, pk=post_id) # pk - primary key
    return render(request, 'aboutall_blog/detail.html', context={'blog_post': blog_post})

portfolio/views.py
from django.shortcuts import render

from portfolio.models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', context={'projects': projects})

def cv(request):
    return render(request, 'portfolio/index.html')

def contacts(request):
    return render(request, 'portfolio/contacts.html')

aboutall_blog/templates/aboutall_blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

        <div class="container text-center">

            <h1>This is my blog</h1>
            <!--{{ posts.count }} - counting objects. blog{{ blogs.count|pluralize }} - if one object - 'blog' otherwize - 'blogs'-->
            <h2>We found {{ posts.count }} post{{ posts.count|pluralize }} for you</h2>
            <!--posts from views-->
        </div>
        <div class="container">
                <div class="col-md-6">
                    {% for post in posts %}

                        <!--url 'detail' - detail from urls.py-->
                        <!--post.id - id of one post from QwerySet-->
                        <a href="{% url 'aboutall_blog:detail' post.id %}"><h2>{{ post.post_title }}</h2></a>
                        <p>{{ post.post_description }}</p>
                        <!--truncatechars:150 - how many characters we want to show-->
                        <p>{{ post.post_fulltext|truncatechars:150 }}</p>
                        <!--date:'M j Y' - date format-->
                        <p>{{ post.post_create_at|date:'M j Y'|upper }}</p>
                        <p>{{ post.post_author }}</p>

                    {% endfor %}
                </div>
        </div>

{% endblock %}

aboutall_blog/templates/aboutall_blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="post-details">
        <h1>{{ blog_post.post_title }}</h1>
        <h2>{{ blog_post.post_description }}</h2>
        <br>
        <h5>{{ blog_post.post_create_at }}</h5>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
      <title>Home</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            <a class="my-nav navbar-brand" href="{% url 'home' %}"> Home</a>
            <div class="d-flex" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item my-nav">
                    <!--aboutall_blog:all_blogs - 'aboutall_blog' (app-name) CALLING name 'all_blogs' in urls.py and urls.py calling function all_blogs in views.py-->
                    <!--a class="nav-link active" aria-current="page" href="{% url 'aboutall_blog:all_blogs' %}">Blog</a-->
                </li>
                <li class="nav-item">
                  <a class="nav-link my-nav" href="{% url 'cv' %}" target="blank">My CV</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link my-nav" href="{% url 'contacts' %}">Contacts</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {% block content %}{% endblock %}


    </body>
</html>

portfolio/templates/portfolio/contacts.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="contact-card card bg-dark text-black">
  <img src="{% static 'portfolio/contacts.jpg' %}" class="card-img">
  <div class="card-img-overlay">
    <h3 class="card-title">Artem Tokar</h3>
    <br>
    <h4 class="card-text"><img class="icon" src="{% static 'portfolio/phone.png' %}"> +34 674 93 06 46</h4>
    <br>
    <h4 class="card-text"><img class="icon" src="{% static 'portfolio/email.png' %}"> artem.tokar13@gmail.com</h4>
    <br>
    <h4 class="card-text"><img class="icon" src="{% static 'portfolio/telegram.png' %}"> @artem_tokar</h4>
  </div>
</div>

{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

    <h1 class="container text-center">Personal portfolio of</h1>
    <h1 class="container text-center">ARTEM TOKAR</h1>
    <div class="container text-center">
        <img src="{% static 'portfolio/me.jpg' %}" class="img img-fluid">

        <h1 class="projects container text-center">PROJECTS</h1>
        <div class="container">
        <div class="row">
        {% for project in projects %}
            <div class="col-sm-4">
            <h2>{{ project.title }}</h2>
            <a target="blank" class="l-flex link-text" href="{{ project.url }}">
            <image src="{{ project.image.url }}" class="img-fluid"></image></a>
            <p>{{ project.description }}</p>
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV-Artem-Tokar</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
</head>
<body>
    <div class="body-cv">
    <!-- main conteiner -->
    <div class="main_conteiner">
        <!--main content-->
        <div class="main_content">

            <!-- About me section -->
            <div>
                <h1 class="about_me_name">Artem Tokar</h1>
                <h3 class="main_content_tittle">Web Applications Developer</h3>
            </div>
            <hr>
            <!--my-education-->
                <div class="my_education">
                    <h3 class="main_content_tittle">Educacion</h3>
                    <h4 class="my_education_name">National University of Oil and Gas</h4>
                    <h5 class="my_education_speciality">Computer systems and nets (Computer engineering)</h5>
                    <h5 class="my_education_speciality">Engineer’s Degree (Ingeniería Superior)</h5>
                    <p class="my_work_experience_time">September 2001 - June 2006 <span class="devider"> | </span> Ukraine</p>
                </div>
                <div class="my_education">
                    <h4 class="my_education_name">Self-Education (Udemy, Stepik, YouTube, others resourses)</h4>
                    <h5 class="my_education_speciality"></h5>
                    <h5 class="my_education_speciality">2021 Complete Python Bootcamp From Zero to Hero in Python (Udemy)</h5>
                    <h5 class="my_education_speciality">Django 3 - Full Stack Websites with Python Web Development (Udemy)</h5>
                    <h5 class="my_education_speciality">Build a Backend REST API with Python & Django (Udemy)</h5>
                    <h5 class="my_education_speciality">Real World Python Test Automation with Pytest (Django app) (Udemy)</h5>
                    <h5 class="my_education_speciality">Intro to Programming in Python (Stepik)</h5>
                    <h5 class="my_education_speciality">Python: Basics and Applications (Stepik)</h5>
                    <h5 class="my_education_speciality">Introduction of Linux (Stepik)</h5>
                    <h5 class="my_education_speciality">Html & CSS basics (Stepik)</h5>
                    <h5 class="my_education_speciality">Introduction to OOP for Python developers (Stepik)</h5>
                    <p class="my_work_experience_time">March 2021 - till today <span class="devider"> | </span> Spain</p>
                </div>
            <hr>
            <!-- my projects section-->
            <div class="mi_projects">
                <h3 class="main_content_tittle">My projects</h3>
                <ol class="my_project_list">
                    <li class="my_projects_item">
                        <span class="my_projects_text">
                            <a href="https://spapostat.pythonanywhere.com/" class="my_project_link">https://spapostat.pythonanywhere.com/</a>
                            ...............
                            <span class="my_project_bracket">[</span> My portfolio <span class="my_project_bracket">]</span>
                        </span>
                    </li>
                    <li class="my_projects_item">
                        <span class="my_projects_text">
                            <a href="https://artemtouch.pythonanywhere.com" class="my_project_link">https://artemtouch.pythonanywhere.com</a>
                            ............
                            <span class="my_project_bracket">[</span> Techblog <span class="my_project_bracket">]</span>
                        </span>
                    </li>
                    <li class="my_projects_item">
                        <span class="my_projects_text">
                            <a href="https://https://remindmy.pythonanywhere.com/" class="my_project_link">https://remindmy.pythonanywhere.com/</a>
                            ..............
                            <span class="my_project_bracket">[</span> SMS-Reminder <span class="my_project_bracket">]</span>
                        </span>
                    </li>
                    <li class="my_projects_item">
                        <span class="my_projects_text">
                            <a href="https://github.com/ArtemTokar13" class="my_project_link">https://github.com/ArtemTokar13</a>
                            ................................
                            <span class="my_project_bracket">[</span> My repository <span class="my_project_bracket">]</span>
                        </span>
                    </li>
                    <li class="my_projects_item">
                        <span class="my_projects_text">
                            <a href="https://github.com/ArtemTokar13/recruitme" class="my_project_link">https://github.com/ArtemTokar13/recruitme</a>
                            .......
                            <span class="my_project_bracket">[</span> Recruitment site <span class="my_project_bracket">]</span>
                        </span>
                    </li>
                </ol>
            </div>

            <hr>

            <!--my work eexperience-->
            <div class="mi_work_experience">
                <h3 class="main_content_tittle">Work Experience</h3>
                <!--Company2-->
                <div class="my_work_experience_list">
                    <h4 class="my_work_experience_position">Manager of support <span class="my_work_experience_company"> Ukrsibbank BNP Paribas </span> </h4>
                    <p class="my_work_experience_time">April 2010 - May 2016 <span class="devider"> | </span> Ukraine</p>
                    <ul class="my_work_experience_duties">
                        <li class="my_work_experience_duty">Concluding contracts for support of bank branches and ATMs in the region.</li>
                        <li class="my_work_experience_duty">Cooperation with local gavernments.</li>
                        <li class="my_work_experience_duty">Rent of premises for bank branches.</li>
                        <li class="my_work_experience_duty">Information support of bank branches.</li>
                    </ul>
                </div>
                <!--Company1-->
                <div class="my_work_experience_list">
                    <h4 class="my_work_experience_position">System administrator<span class="my_work_experience_company"> Ukrsibbank BNP Paribas </span></h4>
                    <p class="my_work_experience_time">June 2006 - April 2010 <span class="devider"> | </span> Ukraine</p>
                    <ul class="my_work_experience_duties">
                        <li class="my_work_experience_duty">Administrating local net (150 workstations, Windows 2000 Server, Active Directory, Lotus Notes).</li>
                        <li class="my_work_experience_duty">Installing and maintening of ATMs Wincor Nixdorf 2100/2050 and Diebold Opteva 562.</li>
                        <li class="my_work_experience_duty">Installing and maintening of point of sale (POS) terminals</li>
                        <li class="my_work_experience_duty">Instalation and updating of software</li>
                        <li class="my_work_experience_duty">Hardware (configuration and instalation)</li>
                        <li class="my_work_experience_duty">LAN (configuration and instalation)</li>
                    </ul>
                </div>
            </div>


        </div>
        
        <!--sidebar-->
        <aside class="sidebar">
            <img class="photo" src="{% static 'ArtemTokar.jpg' %}" alt="my photo">

            <!--contacts section-->
            <div class="contacts_section">
                <h3 class="sidebar_tittle">Contacts</h3>
                <div>
                    <span class="contact_section_type">C:</span>
                    <a class="contact_section_link" href="tel:+34674930646">+34 674 93 06 46</a>
                </div>
                <div>
                    <span class="contact_section_type">E:</span>
                    <a class="contact_section_link" href="mailto:artem.tokar13@gmail.com">artem.tokar13@gmail.com</a>
                </div>
            </div>
            <!--tech skills-->
            <div class="tech_skills">
                <h3 class="sidebar_tittle">Technologies</h3>
                <ul class="skills_list">
                    <li class="skills_item"> <span class="skills_item_text"> Python3 </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Django </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Django REST framework  </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> web2py  </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> JavaScript  </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> SQL </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> BASH </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> HTML5 </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Bootstrap </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> CSS3 </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> GIT </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Pytest </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Postman </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Vagrant </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> VirtualBox  </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> VMWare  </span></li>
                </ul>
            </div>
            <!--Languages-->
            <div class="soft_skills">
                <h3 class="sidebar_tittle">Languages</h3>
                <ul class="skills_list">
                    <li class="skills_item"> <span class="skills_item_text"> Ukrainian - native </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Russian - native </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> Spanish - advanced </span></li>
                    <li class="skills_item"> <span class="skills_item_text"> English - intermediate </span></li>
                </ul>
            </div>
        </aside>
    
    </div>
    </div>

</body>
</html>